# taskconfig.yaml: Main task configuration
# ----------------------------------------
# workspace:
# TODO: rearrange the lay out
workspace: "/home/lee/code/isaactasks/ingenuity"
env_cfg_path: "/home/lee/code/isaactasks/ingenuity/source/ingenuity/ingenuity/tasks/direct/ingenuity/ingenuity_env.py"
logs_path: "/home/lee/code/isaactasks/ingenuity/logs/rl_games/ingenuity_direct"
description: "to NASA's Ingenuity helicopter to navigate to a moving target"


# training settings:
task: Template-Ingenuity-Direct-v0
num_envs: None
seed: None
checkpoint: None
max_iterations: None
python_env: /home/lee/anaconda3/envs/env_isaaclab/bin/python